[build]
  publish = "dist"
  command = "npm run build"
[build.processing.html]
  pretty_urls = false
[[redirects]]
  from = "/media-v3"
  to = "/media"
  status = 301
[[headers]]
  for = "/_astro/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
